pablosanjose/Quantica.jl

src/KPM.jl, src/Quantica.jl, src/bandstructure.jl, src/convert.jl, src/diagonalizer.jl, src/hamiltonian.jl, src/iterators.jl, src/lattice.jl, src/mesh.jl, src/model.jl, src/parametric.jl, src/presets.jl, src/tools.jl, test/runtests.jl, test/test_hamiltonian.jl, test/test_lattice.jl, test/test_mesh.jl, test/test_model.jl
This migrates the Elsa.jl codebase to Quantica.jl, with minor changes to adapt to the change of name
=> Transfer Elsa.jl

src/convert.jl, src/hamiltonian.jl, src/model.jl, src/tools.jl, test/test_hamiltonian.jl, test/test_model.jl
Before, an `onsite(3)` would be applied (with a warning) to a sublattice of orbital dimension `N>1` as an identity `3I`. This was always a likely bug (inconsistent model with orbital dimensions). We now error instead of showing a warning, pointing the user to `onsite(3I)` if case she really intends to implement an identity matrix.
This check is done by static dispatch through `toeltype` when building the Hamiltonian. It should therefore have no runtime overhead. It also allows us to remove the `checkmodelorbs` check (that previously issued the warning), which was fragile and ugly (it relied on applying a model term to some random sites).
=> Strict model dimensions

src/Quantica.jl, src/model.jl, test/test_model.jl
Closes #15 
This introduces `onsiteselector!(m::TightbindingModel; kw...)` and `hoppingselector!(m::TightbindingModel; kw...)` that overwrites the selectors of all onsite or hopping terms in model `m`, respectively, with the keywords `kw` corresponding to `onsiteselector` and `hoppingselector`
=> onsiteselector!(model) and hoppingselector!(model)

src/Quantica.jl, src/hamiltonian.jl, src/model.jl, test/test_model.jl
Closes #21
This implements [this proposal](https://github.com/pablosanjose/Quantica.jl/issues/21#issuecomment-611493364)
To make code simpler we have moved the `forcehermitian` field of `OnsiteTerm` and `HoppingTerm` into their respective `selector::Selector` fields. In a way, this move is conceptually not ideal (how is hermiticity a property of a site selector?), but since site/link selection and `forcehermitian` are both used in the same context (hamiltonian building) the code simplification seems worth it for now.
=> API simplification: merge onsiteselector!/hoppingselector! into onsite/hopping

src/Quantica.jl, src/hamiltonian.jl, src/model.jl, test/test_model.jl
Addresses part of #19 by removing the `onsiteselector` and `hoppingselector` functions from the public API. With this PR there is only one way to restrict sites/hoppings, which is is through the `kw` of `onsite(...; kw...)` and `hopping(...; kw...)`
=> Remove Selectors from public API

src/bandstructure.jl, src/hamiltonian.jl, src/mesh.jl, test/test_mesh.jl
Closes #20
This PR removes the `marchingmesh(npoints...)` method, and only defaults to a `range(-π,π,length=resolution)`  when building a mesh by calling `bandstructure(h; resolution)`
=> Simplify marchingmesh

Manifest.toml, Project.toml, src/Quantica.jl, src/hamiltonian.jl, src/lattice.jl, src/model.jl, src/parametric.jl, src/tools.jl, test/test_hamiltonian.jl
Closes #16
The only API changer is `onsite!` --> `@onsite!` and `hopping!` --> `@hopping!`. These macros parse the structure of the anonymous function to extract `params`. It also supplements `params` with a filler `kw...` so that parametric Hamiltonians can accept arbitrary `ElementModifier`s with matching or non-matching `params`
The only shortcoming I see here is that this PR forces a `@onsite((args...; params...) -> body; kw...)` kind of syntax, always. You cannot do `@onsite(func; kw...)` with an existing `func`, since (1) that `func` could have different methods with different `kwargs` and (2) once compiled, there is no way to extract its kwargs without digging into the method tables.
The next step this PR enables is a definition of `bloch` and `bandstructure` that automatically …
=> @onsite! and @hopping! macros for automatic parameter declaration

src/bandstructure.jl, src/hamiltonian.jl, src/lattice.jl, test/test_hamiltonian.jl
This PR leave only the `bloch(h, ϕs)`/`bloch!(matrix, h, ϕs)` syntax to obtain the Bloch Hamiltonian of `h`. The `bloch(h)` syntax for the unit cell Hamiltonian remains. However the `h(ϕs)` and `h(ϕs...)` forms are *also* removed.
=> Remove bloch(h, ϕs...), leave only bloch(h, ϕs)

src/hamiltonian.jl, src/model.jl, src/tools.jl, test/test_hamiltonian.jl, test/test_model.jl
Addresses one of the points in #19
This simplifies and extends the `sublats` keyword in `hopping`. A hoppings from sublat `:A` to sublat `:B` is now always denoted with `:A => :B`. The PR also allows for broadcasting between two groups of sublattices `(:A, :B) .=> (:A, :B)` (equivalent to `(:A => :A, :B => :B)`), and even direct product, `(:A, :B) => (:C, :D)` (equivalent to `(:A=>:C,:A=>:D,:B=>:C,:B=>:D)`).
Updated and extended also the docstrings for `hopping` and `onsite`, and added an internal method `Quantica.sublats(model)` that returns the sublats of each term in `model`.
=> Unified Pair syntax for sublats kwarg in hopping

src/model.jl, test/test_model.jl
Until now, the dn kwarg allowed tuples of integers. Since `dn` can easily be the result of a linear algebra computation, it makes sense to allow also Vectors or SVectors. This is implemented by this PR.
=> Allow SVectors and Vectors in hopping's dn kwarg

Manifest.toml, Project.toml, src/model.jl
As the issue [#8](https://github.com/invenia/ExprTools.jl/issues/8) in ExprTools is now fixed and tagged (0.1.1), this ups the compat and removes the workaround we had for this issue
=> Upgrade to ExprTools 0.1.1

docs/make.jl, src/hamiltonian.jl, src/lattice.jl, src/model.jl, src/parametric.jl
Docstrings with doctests that include @meta sections for setup display the @meta code in the REPL. Since Documenter 0.23 it is [recommended](https://juliadocs.github.io/Documenter.jl/stable/man/doctests/index.html#Module-level-metadata-1) to set up the environment for doctests in the make.jl file
This PR does that.
=> Documenter: module-level DocTestSetup

src/hamiltonian.jl, src/lattice.jl, test/test_hamiltonian.jl
In this PR we introduce a Superlattice-specific feature: boolean masks
A `Superlattice` is a combination of a `Lattice` (typically periodic) and a `Supercell` (a region of space that is filled by the lattice along some axes). Likewise, a `Hamiltonian{<:Superlattice}` is a Hamiltonian defined on a `Lattice` plus a `Supercell` for that `Lattice.
When you do `unitcell(h, ...)`, where `h` is a `Lattice` or a `Hamiltonian`, what happens behind the scenes is that `supercell(h,...)` is called first, which produces a `s::Superlattice` or `s::Hamiltonian{<:Superlattice}`, respectively. Only then the superlattice's supercell is expanded into a unitcell via a call to `unitcell(s)`.
This PR allows combining two or more `Superlattice` or `Hamiltonian{<:Superlattice}` using boolean operators, `&`, `|` …
=> Boolean masks

src/hamiltonian.jl, src/parametric.jl, test/test_hamiltonian.jl
Closes #35 
The fix resets the modified elements of a ParametricHamiltonian to the values in the base Hamiltonian before applying the modifiers. To do this efficiently the complete list of modified nonzeros are computed at build time. Then, modifiers are applied cumulatively one after the other, instead of being applied always to the base values as before.
This PR also includes a fix for the computation of number of hoppings in a Hamiltonian, so that only non-zero hoppings are computed in the sparse case (like in the dense case). Otherwise an `optimize!`d Hamiltonian (such as a ParametricHamiltonian) misreports its coordination.
=> Issue#35, cumulative application of modifiers in ParametricHamiltonian

src/hamiltonian.jl, src/model.jl, src/parametric.jl, src/tools.jl, test/test_bandstructure.jl, test/test_hamiltonian.jl, test/test_model.jl
Closes #37 
Settled on `plusadjoint` instead of `addadjoint`
The performance drop is exactly as expected. When `plusadjoint=true` there are two hoppings to process, so `applyterm!` for those two terms take almost twice as long as the single `forcehermitian=true` term before the PR, that processed elements and their adjoints in the same loop.
=> Remove `forcehermitian`, add `plusadjoint`

src/presets.jl, test/test_lattice.jl
E.g. `RegionPresets.circle(3, (1,0))` is a circle centered at `(1,0)` of radius 3. If unspecified (e.g. `RegionPresets.sphere(3)`), the center is at the origin.
=> Add optional centers to RegionPresets

src/Quantica.jl, test/test_hamiltonian.jl, test/test_lattice.jl
We add `SA` to the other StaticArrays exports. Although `SA` would be enough for everything, we don't unexport the old ones, as they can be preferred in some situations (more explicit)
=> Export SA from StaticArrays

src/hamiltonian.jl, src/plot.jl
The code to iterate over non-zero elements in a Hamiltonian involved a full-fledged iterator `EachindexNonzero`. The resulting code was far too complex and had actually some subtle bugs. This refactors all that code into a very simple filter/nested generator that is actually equally fast in local tests and is free of the bugs of the old code. I wasn't able to produce a MWE of the old bug, but the real world case where the bug was found is resolved by this PR, so this goes without tests.
=> RFC: nonzero indices iterator

src/hamiltonian.jl, src/lattice.jl, src/tools.jl
Since StaticArrays 0.12.2, `iszero(::SVector{0})` errored instead of being `true`. Until that is fixed, we use a `iszero_or_empty` helper for zero checks on cell distances `dn`.
=> Fix for StaticArrays 0.12.2 regression #778

src/model.jl
This PR removes a workaround for issue [ExprTools#8](https://github.com/invenia/ExprTools.jl/issues/8) now that the fix is merged. I think old PRs #31 and #32 were failing tests because of the Manifest.toml pinning the version of ExprTools used (not 100% sure).
=> Remove workaround for ExprTools#8

src/KPM.jl, src/bandstructure.jl, src/diagonalizer.jl, src/hamiltonian.jl, src/parametric.jl, test/test_bandstructure.jl
Closes #28 
This implements the `bandstructure(::ParametricHamiltonian, mesh)` and the `bandstructure(::Union{Hamiltonian,ParametricHamiltonian}, mesh; cut =...)` functionality. 
This new feature is quite powerful. It allows to treat parameters in a `ParametricHamiltonian` as equivalent to Bloch phases when computing `bandstructure(ph::ParametricHamiltonian, mesh)`. The `mesh` should be a discretization of the parameter space ⊗ Brillouin zone for `ph`. Each vertex `v` of `mesh` is interpreted as `v = (p₁,..., pᵢ, ϕ₁,..., ϕⱼ)`, with parameter values `p` coming before Bloch phases `ϕ`.
A possible application: obtain the bandstructure of a planar Josephson junction as a function of parallel momentum and superconductor phase difference. In general, this is useful when needing to compute the …
=> Parametric bandstructures with cuts

src/hamiltonian.jl, src/lattice.jl, src/plot_makie.jl, src/plot_vegalite.jl, src/tools.jl
... with tooltips, and pan/zoom!
Example
```
julia> using Quantica, VegaLite
julia> h = LatticePresets.honeycomb() |> hamiltonian(hopping(1)) |> unitcell(8);
julia> vlplot(h)
```
=> Plots of Hamiltonians with VegaLite

src/hamiltonian.jl, src/lattice.jl, src/tools.jl, test/test_hamiltonian.jl
This is a subtle one. In the old times, a `ϕs::Tuple` passed to `bloch!`, say, had to be converted to an `SVector`. This was done by the `toSVector` helper function. It assumed, however, that all elements of `ϕs` were `::Number`s. However, since `bloch!` was extended to support `ParametricHamiltonian`s, the elements of `ϕs` can be anything (e.g. an `SVector` or `SMatrix` parameter). In such a case, `toSVector` had no convenient dispatch. 
This PR simply changes `toSVector(::NTuple{N,Number})` to `toSVector(::NTuple{N,Any})` to enable this more general case. 
[It also expands some other `NTuple{N,<:Any}` (uniform but arbitrary types) to `NTuple{N,Any}` (completely arbitrary types), which was the intended meaning.]
Let's see if tests pass...
=> Allow toSVector(::NTuple{N,Any})

src/KPM.jl
The aim of this PR is to enhance the performance of the Kernel Polynomial Method (KPM) momenta calculation already built on KPM.jl, by using the recently implemented multithreading approach available on julia v1.3+ (see #https://julialang.org/blog/2019/07/multithreading/). 
The calculation of KPM momenta doesn't allow for an easy parallelisation scheme due to the sequential nature of the momentum generator algorithm. Although this might suggest that the parallelisation at this level is not a viable option, it is indeed possible to distribute on multiple threads the matrix operations for each step of the momenta calculation (see `iterateKPM()`). Typically, the overhead of distributing tasks over all available threads N times (being N the order of the KPM expansion) leads to a significant …
=> Multithread processing in KPM

src/KPM.jl, test/test_KPM.jl
The clever scalar version of the KPM iteration inherited from Elsa was broken. Since Julia 1.3 we have 5-argument `mul!` that implements a similar scalar algorithm. It is also multithreaded to boot. This PR uses such facility, and fixes KPM in the process (I used the computation in https://discourse.julialang.org/t/kernel-polynomial-method/34240/3 as reference). A side effect is that the code is again much clearer and closer to the original algorithm.
=> Fix broken KPM scalar optimization, use 5-arg mul! instead

src/Quantica.jl, src/bandstructure.jl, src/diagonalizer.jl, src/mesh.jl, src/parametric.jl, src/plot_vegalite.jl, src/tools.jl, test/test_bandstructure.jl, test/test_mesh.jl
Closes: #64 
This implements the proposal by @BacAmorim in #64 that unifies `marchingmesh` and `linearmesh` to both construct subtypes of `MeshSpec`. This kind of type holds information necessary to build a `Mesh` and a lift function, once `h` is provided. Multiple dispatch on functions `buildmesh(spec, br)` and `buildlift(spec, br)` take care of that, where `br` is the Bravais matrix of `h` (which is actually the only thing required to build the mesh from the spec). 
We thus now have a new API for bandstructures, which is the one a typical user is likely to use, based on MeshSpec objects
```
bandstructure(::Union{Hamiltonian,ParametricHamiltonian},  ::MeshSpec; kw...)
```
where we currently have two types of `MeshSpec`, `MarchingMeshSpec` and `LinearMeshSpec`, constructed using …
=> RFC: MeshSpec and linearmesh, with support for bandcuts (i.e. lifting)

src/lattice.jl, src/tools.jl, test/test_hamiltonian.jl, test/test_lattice.jl
There was a bad bug in `unitcell`. This `h = LatticePresets.honeycomb() |> hamiltonian(hopping(1, range = 1/√3)) |> unitcell((1,-1), region = r -> abs(r[2])<10)` failed to produce a graphene nanoribbon, as it included only one vertical row of sites in a unitcell, not an armchair chain. The reason was an ugly bug in the `unitcell` core function `pinvmultiple` that computes an integer matrix that is an integer multiple of the supercell pseudoinverse. That multiple was computed as the determinant of the R factor in the QR decomposition of the supercell matrix `s`, but that is only actually valid if the latter is square and invertible. The (or at least one) correct multiple is `det(s's)`. 
Hat tip to @baggepinnen [in discourse](https://discourse.julialang.org/t/rational-pseudo-inverse-matrix/4 …
=> Bug fix in unitcell

Project.toml, README.md, src/KPM.jl, src/Quantica.jl, src/bandstructure.jl, src/diagonalizer.jl, src/greens.jl, src/hamiltonian.jl, src/lattice.jl, src/mesh.jl, src/model.jl, src/tools.jl, test/test_greens.jl
This PR implements our first solver for Green's functions. It takes the bandstructure of a periodic Hamiltonian in arbitrary dimensions `L` and constructs a `GreensFunction{<:BandGreenSolver}` object that can be used to generate the Green's function matrix of the Hamiltonian between two arbitrary unit cells.
The method is a generalization to arbitrary dimensions and unit cell distance of the classical tetrahedron method, which takes a linearization of a dispersion and eigenstates within a tetrahedron and integrates the resolvent on it it analytically. Each simplex in each band in the bandstructure is one such tetrahedron. The analytical solution used here is not published, but it is ultimately a form of the solution given in https://iopscience.iop.org/article/10.1088/0022-3719/15/34/009 …
=> WIP: Green's functions from bandstructures  (generalized tetrahedron method)

Project.toml, README.md, src/KPM.jl, src/Quantica.jl, src/hamiltonian.jl, src/model.jl, src/presets.jl, src/tools.jl, test/test_KPM.jl, test/test_hamiltonian.jl, test/test_model.jl
This introduces a new API to specify kets, for e.g. KPM routines. It introduces a `KetModel` type, constructed by the exported function `ket(a; kw...)` (analogous to `OnsiteModel`s created by `onsite`). `a` specifies ket amplitudes (as a constant or a function) and `kw` specifies which sites to apply the amplitude to (the `kw` are passed to `siteselector`). There is an extra `kw` that is `normalized`, that normalizes the ket when true.
As an example, a `KetModel` such as `ket(r -> norm(r)^2; sublats = :A, region = RegionPresets.circle(10), normalized = true)` can be used to create a normalized ket with amplitude proportional to `|r|^2` only of sublattice `:A` within a 10-radius circle centered at the origin.  Bear in mind that `ket` creates a *model*  independently of a Hamiltonian (just …
=> New ket API for KPM

src/model.jl, src/presets.jl
Fixes a regression due to making `Region <: Function`. For some obscure reason that makes `unitcell(region = ::Region)` allocate like crazy (in the supercell step). This was innocently introduced in #80. The present PR reverts that, to recover small allocations, like in 
```
julia> @time LatticePresets.honeycomb() |> hamiltonian(hopping(1, range = 1/√3)) |> unitcell(region = RegionPresets.circle(300))
0.178050 seconds (360 allocations: 76.432 MiB)
Hamiltonian{<:Lattice} : Hamiltonian on a 0D Lattice in 2D space
Bloch harmonics  : 1 (SparseMatrixCSC, sparse)
Harmonic size    : 652966 × 652966
Orbitals         : ((:a,), (:a,))
Element type     : scalar (Complex{Float64})
Onsites          : 0
Hoppings         : 1956506
Coordination     : 2.9963367158473795
```
=> Fix regression using Region

README.md, src/Quantica.jl, src/hamiltonian.jl, src/lattice.jl, src/model.jl, src/parametric.jl, src/plot_makie.jl, src/plot_vegalite.jl, src/presets.jl, src/tools.jl, test/test_hamiltonian.jl, test/test_lattice.jl, test/test_model.jl
Closes #82 
This PR implements the `indices` kwarg in `Selector`s, and in doing so introduces some heavy refactoring of the whole `Selector` engine. See the updated `siteselector` and `hopselector` docstrings for details.
We now have `ResolvedSelector` in addition to `SiteSelector` and `HopSelector`. `ResolvedSelector` is produced by `resolve(::Selector, ::AbstractLattice)`, which now simply replaces sublat names with sublat indices, but does not do any further clever transformation of selection specs (i.e. things like `(:A, :B) => (:C, :D)` become `(1,2) => (3,4)`, but not (1=>3, 1=>4, 2=>3, 2=>4)` anymore). The actual interpretation of the different selector directives is done when querying whether a site or site pair is selected by the `ResolvedSelector`. This is now done using the …
=> `indices` kwarg in selectors

src/hamiltonian.jl, src/model.jl, test/test_hamiltonian.jl, test/test_model.jl
Closes #86 
Nothing much to discuss here. Just a note on implementation. Instead of doing a tree search with NearestNeighbors strictly in the (rmin, rmax) range, we still do a target candidate search with rmax, and then rely on the selector check to exclude those with norm below rmin. Also, eps(T) padding of range is done to ensure that `range = (1,1)` selects anything at distance 1, regardless of floating point errors.
=> Allow range = (rmin, rmax)

src/hamiltonian.jl, src/lattice.jl, src/model.jl, test/test_hamiltonian.jl
There was an edge case opened by #87 whereby a min_range larger than several bravais vectors would make the search algorithm for hoppings bail out too soon and link nothing. This resolves the issue by not allowing the search to stop until min_range is surpassed
=> Bugfix min_range

src/plot_vegalite.jl
This makes it equivalent to the behaviour with Makie. 
Before:
After:
=> Draw intercell hoppings as full lines in VegaLite

src/hamiltonian.jl, src/plot_makie.jl
This requires Makie 0.11.1 or later. Since it is not a direct Quantica dependence, the user should make sure that their installed version is sufficiently new.
Previously the points in Makie scatter plots were of a fixed size in pixel space. Since 0.11.1 we can now set a fixed size in Scene space. This allows sites plotted with the default unshaded method (fast) to scale just as shaded sites. So now sites at two zoom levels are scaled as expected
This PR also introduces a fix to `linkoffset` plot keyword, so that `linkoffset = 0` (the default) corresponds to links that just touch the site borders, as in the plots above
=> Makie plots: unshaded sites that scale correctly with zoom

README.md, src/Quantica.jl, src/hamiltonian.jl, src/lattice.jl, src/model.jl, src/tools.jl, test/test_hamiltonian.jl
This implements a new default behavior for the `range` keyword in `hopping`. This default used to be hard-coded to `range = 1`, which is rather arbitrary and can lead to surprises, as discussed in #85.
With this PR, the default for `hopping` is `range = nrange(1)`, where `nrange(n)` creates a `NeighborRange` object that represents the distance between nᵗʰ-order nearest-neighbors of a lattice's sites. `nrange` is a new exported function. 
The default behavior for something like `hopping(1)` then corresponds to nearest neighbors only (`nrange(1)`)
```
julia> h = LatticePresets.honeycomb(a0 = 0.24) |> hamiltonian(hopping(1))
Hamiltonian{<:Lattice} : Hamiltonian on a 2D Lattice in 2D space
Bloch harmonics  : 5 (SparseMatrixCSC, sparse)
Harmonic size    : 2 × 2
Orbitals         : ((:a,), …
```
=> NeighborRange default for hopping range

.github/workflows/ci.yml, src/lattice.jl, test/test_lattice.jl
There was a bug that broke the use of `combine` on more than two lattices.
=> Bugfix in combined_offsets

README.md, src/convert.jl, src/hamiltonian.jl, src/lattice.jl, src/plot_makie.jl, src/presets.jl, src/tools.jl, test/test_lattice.jl
This is quite a breaking change. It changes the `lattice(bravais, sublats...; kw...)` syntax to `lattice(sublats...; bravais = ..., kw...)` syntax. Any user code that uses this method should be updated.
Examples
```
julia> lattice(sublat((0, 0)); bravais = (1, 0), dim = Val(3))
Lattice{3,1,Float64} : 1D lattice in 3D space
Bravais vectors : ((1.0, 0.0, 0.0),)
Sublattices     : 1
Names         : (:A)
Sites         : (1) --> 1 total per unit cell
julia> lattice(sublat((0, 0)); bravais = ((1, 0), (0, 1)), dim = Val(3))
Lattice{3,2,Float64} : 2D lattice in 3D space
Bravais vectors : ((1.0, 0.0, 0.0), (0.0, 1.0, 0.0))
Sublattices     : 1
Names         : (:A)
Sites         : (1) --> 1 total per unit cell
```
This has several advantages. For example we can override the Bravais vectors of a …
=> Move bravais to kwarg

src/convert.jl, src/hamiltonian.jl, src/lattice.jl, test/test_lattice.jl
As mentioned in the cancelled #93 we need to complete the ways we provide to change a lattice, or to build one lattice from another. At the moment we cannot change the Bravais matrix, the type, the embedding dimension or the sublattice names of a lattice after creation. This PR, that builds on #94, does just that. It provides a method `lattice(lat; kw...)` where `kw` are any of the kwargs for lattice creation (`bravais`, `dim`, `type` and `names`). To do this elegantly we needed to move `bravais` to a kwarg, which was done in #94.
From the implementation point of view, the key of this PR is to keep the mutation as efficient as possible. If we're only changing Bravais vectors, there is no need to touch the site position array or sublattice offsets. In contrast, if we're changing the …
=> lattice(lat; kw...)

src/plot_vegalite.jl, src/tools.jl
Introduces a `range` kwarg in vlplot to constrain the plot range, in both x and y, or only in y
It also corrects a bug that didn't allow to specify sizex != sizey
=> VegaLite plot range

src/Quantica.jl, src/model.jl, test/test_model.jl
We need a way to specify excluded site indices and sublattices in selectors. Here we introduce a `not` wrapper that allows such a thing. For example, to create a random potential in all sites but the first
```
hamiltonian(lat, onsite(r -> randn(), indices = not(1)))
```
This can become quite complex, and includes hoppings, with things like
```
parametric(h, @onsite!(o -> o + randn(); sublats = not(:A)), @hopping!(t -> 2t; indices = (not(1:3) =>4:6, not(4 => 5))))
```
This can become a way to create vacancies in a system. For that, however, we need to support full `siteselector`s in `unitcell`, combined with the `not` functionality here to encode vacancy site indices. This latter functionality is currently not available, since unitcell only supports a `region` keyword.
=> Not wrapper

src/hamiltonian.jl, src/lattice.jl, src/model.jl, src/tools.jl, test/test_hamiltonian.jl
This was one tricky refactor, as it touches some of the oldest parts of Quantica. It generalizes the `supercell` routines to take arbitrary SiteSelectors. Before, `supercell` just took a `region` kwarg that was used to constrain any non-periodic direction of a superlattice (this then extended to `unitcell` too). With this PR we can specify other constraints, such as `indices` or `sublats` when building a new supercell or unitcell.
As an example application, we can combine this with the `not` wrapper from #97 to create vacancies by index (i.e. instead of by position). First create a Hamiltonian without vacancies, and plot it to locate the indices for the desired vacancies
```
using VegaLite
h = LatticePresets.honeycomb() |> unitcell(region = RegionPresets.circle(10)) |> …
```
=> Generalize `unitcell` and `supercell` to use generic `SiteSelector` machinery

src/plot_vegalite.jl, src/tools.jl
`vlplot(h::Hamiltonian, digits = 5)` is the default.
=> Control significant digits in VegaLite plot tooltips

src/hamiltonian.jl, src/iterators.jl, src/lattice.jl, src/model.jl, src/tools.jl, test/test_model.jl
After #80 we lost the ability to use a ket in KPM calculations with an `SMatrix` eltype. We were restricted to scalar eltypes for Hamiltonians with scalar eltypes and `Quantica.orbitaltype(h)::SVector` eltype otherwise. However, it is useful to allow kets with SMatrix eltype, as an extension of the `SVector` eltype. It is useful when using `randomkets` and wanting to have some correlation between individual random kets. Then, instead of N correlated random kets we can have a single one with SMatrix eltype. 
Example (relevant for Nambu stochastic trace KPM)
```
h = LatticePresets.honeycomb() |> hamiltonian(hopping(I), orbitals = Val(2)) |> unitcell(100) |> unitcell
k = randomkets(n, r -> cis(2π*rand()) * SA[1 0; 0 -1])
dosKPM(h, kets = k)
```
Note that `Matrix(k, h)` is actually an N×n …
=> Kets : support `SMatrix` eltype

src/plot_makie.jl
Makes lightning a bit more realistic with Makie.
Before (`plot(b, ssao = false)`):
After (`plot(b, ssao = true)`):
=> Add ambient occlusion (`ssao = true`) in Makie `plot`

src/plot_vegalite.jl
In preparation for #103, we add the ability to specify (site-dependent) opacity, size and color of sites and links in VegaLite plots of Hamiltonians. The `vlplot` keywords are now:
```
- `size = 800`: the `(width, height)` of the plot (or `max(width, height)` if a single number)
- `points = false`: whether to plot points on line plots
- `labels`: labels for the x and y plot axes. Defaults `("φ/2π", "ε")` and `("x", "y")` respectively
- `scaling = (1/2π, 1)`: `(scalex, scaley)` scalings for the x (Bloch phase) and y (energy) variables
- `xlims = missing` and `ylims = missing`: `(xmin, xmax)` and `(ymin, ymax)` to constrain plot range
- `bands = missing`: bands to plot (or all if `missing`)
- `axes = (1,2)`: lattice axes to project onto the plot x-y plane
- `digits = 4`: number of …
```
=> More VegaLite plot directives

src/hamiltonian.jl, src/tools.jl, test/test_bandstructure.jl
This introduces an unexported `unflatten(vec, h)` that turns a flattened vector (e.g. eigenstate produced by using a `flatten` blochtype) to another `vec´` of `length(vec´) = size(h,1)` and `eltype(vec´) = orbitaltype(h)`. That is, `unflatten` restores the eigenstate that would have been obtained without flattening the Hamiltonian. 
This is required to make progress in generalizing #111 to multiorbital Hamiltonians.
=> Unflatten: restore orbital structure into elements

src/plot_vegalite.jl
Closes #103 
The strategy is to visualize the lattice (like with `vlplot(h)`) but specifying functions for one of possible site or link properties that employ the wavefunction to generate the property value. There are 6 available channels, 3 for sites and 3 for links, corresponding to size, color and opacity. 
Example using the site size and site color channels:
```
julia> h = LatticePresets.honeycomb() |> hamiltonian(hopping(I)) |> unitcell(10) |> unitcell;
julia> sp = states(spectrum(h));
julia> using LinearAlgebra;
julia> vlplot(h, sp[:,1], sitecolor = psi -> norm(psi), sitesize = psi -> 200*norm(psi))
```
Perhaps we could try to be clever with scaling (to avoid needing that 200 there?)...
=> VegaLite plots of wavefunctions

src/hamiltonian.jl, src/tools.jl, test/test_hamiltonian.jl
This PR allows one to do basic algebra with Hamiltonians (that share lattice and orbital structure). This includes `^`, `*`, `+`, `-` and addition of the identity `I`.
An example
```
julia> h = LatticePresets.honeycomb() |> hamiltonian(hopping(I), orbitals = (Val(2), Val(1))) |> unitcell(2)
Hamiltonian{<:Lattice} : Hamiltonian on a 2D Lattice in 2D space
Bloch harmonics  : 5 (SparseMatrixCSC, sparse)
Harmonic size    : 8 × 8
Orbitals         : ((:a, :a), (:a,))
Element type     : 2 × 2 blocks (Complex{Float64})
Onsites          : 0
Hoppings         : 24
Coordination     : 3.0
julia> 2h^2 + h
Hamiltonian{<:Lattice} : Hamiltonian on a 2D Lattice in 2D space
Bloch harmonics  : 13 (SparseMatrixCSC, sparse)
Harmonic size    : 8 × 8
Orbitals         : ((:a, :a), (:a,))
Element type     : 2 × 2 …
```
=> Algebra with compatible Hamiltonians

src/hamiltonian.jl, src/plot_vegalite.jl
Closes #115 
Upon `using VegaLite`, two new types are exported, `DensityShader` and `CurrentShader` that can be passed to any site or link shader in `vlplot` (in addition to the old options). `CurrentShader(axis; kernel = 1, transform = identity)` can be used to represent the current along a given axis, using a given site kernel, and transformed under a given `transform` function. Similarly `DensityShader(; kernel = 1, transform = identity)` can be used to compute the density (which is equivalent to `psi -> real(transform(psi' * kernel * psi))` in the "old" API).
Example: persistent currents in a the superposition of two low-energy eigenstates in a square-lattice ring
```
julia> h = LatticePresets.square() |> hamiltonian(hopping(I)) |> unitcell(region = r -> 7 < norm(r) < 15);
julia> st = …
```
=> Currents and Densities in vlplot

Project.toml, src/Quantica.jl, src/hamiltonian.jl, src/lattice.jl, test/test_hamiltonian.jl
This is the result of a stress test on the unitcell routines to catch edge cases. We want to guarantee that any `unitcell(h, sc)` with any full-rank `sc` does not change the coordination of the resulting Hamiltonian. To achieve that we needed to correct some bugs and edge cases. Long story short, we were assuming supercell definitions that were slightly different when building the superlattice and the Hamiltonian (position-based vs dn-based). Now both should be consistent (position-based). We also need to be strict about which sites end  up in the final lattice: they should be only those within the bounds of the supercell, no hanging sites. Also, we needed to be a little more conservative in the scan of dn space when building the supercell.
Now tests over a full range of full-rank …
=> Unitcell stress test: coordination should not change with full-rank supercells

src/bandstructure.jl, src/greens.jl, src/plot_makie.jl, src/plot_vegalite.jl
`Bandstructure{D}` objects contain the D-dimensional k-space mesh (called `kmesh`), in addition to the (k, ϵ) mesh inside of each `Band`. This is redundant and can easily lead to bugs if we at some point assume that the `kmesh` is a D projection of the `Band` meshes in D+1 dimensions. It is not, in general, as `Bands` can have missing vertices, or in the future even might have more vertices than `kmesh` if they have been "refined".
This PR removes `kmesh` and makes `Bandstructure{D}` stand for a collection of bands, each defined as a mesh in D dimensions. Hence, a 1D bandstructure as a function of phase `ϕ₁` is now `Bandstructure{2}`, where the 2 stands for the dimensions of `(ϕ₁, ϵ)` space.
=> Remove kmesh from Bandstructure

Project.toml, src/Quantica.jl, src/bandstructure.jl, src/diagonalizer.jl, src/hamiltonian.jl, src/iterators.jl, src/mesh.jl, src/parametric.jl, src/plot_makie.jl, src/plot_vegalite.jl, src/tools.jl, test/test_bandstructure.jl, test/test_mesh.jl
Closes #122, #123 
This PR implements a variant of the approach hashed out in the above issues (with some significant variations), designed to 
- Gracefully deal with degeneracies, including topologically non-trivial ones such as Dirac points
- Allow O(1) access of simplices in a bandstructure
I'm rather happy with the design including here. It is both cleaner, more correct and (sometimes) faster than what we have in master regarding degeneracy resolution in `bandstructure`.
For context, master deals with d-order degeneracies by keeping d copies of the degenerate eigenvalues, and co-diagonalizing their eigenvectors with some kind of a velocity operator (be it using DualNumbers or finite differences). The codiagonalizer thing was tricky and rather inelegant (somewhat "heuristic" if you're …
=> Taking degeneracies seriously

src/bandstructure.jl, src/diagonalizer.jl, src/iterators.jl, src/plot_vegalite.jl, test/test_bandstructure.jl
Complex eigenvalues made the merging of degeneracies in bandstructure trip. We fix this by making a smarter `Subspace` type that converts complex eigenvalues to the type of momenta. We also make sure the `approxruns::Runs` iterator deals with complex eigenvalues correctly.
=> Fix for complex spectra

src/plot_vegalite.jl
We optimize vegalite plots by using :line instead of :rules. This PR includes line cuts using NaN when the line is discontinuous
=> Line skips in VegaLite band plot

src/bandstructure.jl, src/plot_vegalite.jl, test/test_bandstructure.jl
To see the tooltips one must hover a vertex in the plot. If we don't plot the vertices (with `vlplot(b, points = true)`), we need to hunt for them along the band lines:
=> Vertex degeneracies as tooltips in vegalite bandstructures

src/Quantica.jl, src/lattice.jl, src/presets.jl, test/test_lattice.jl
Closes #121 
This introduces boolean operators `&`, `I`, `xor` and `!` for `RegionPresets.Region`s
This also fixes a ~little~ bug in `supercell` that could lead to empty lattices when searching for sites did not immediately turn up a candidate. 
It also introduces convenience aliases `LP` for `LatticePresets`, `HP` for `HamiltonianPresets` and `RP` for `RegionPresets`
Usage example
```
h = LatticePresets.honeycomb() |> hamiltonian(hopping(-1)) |> 
unitcell(region = xor(RP.circle(10), RP.circle(6, (3,0)), RP.circle(6, (-3,0))))
```
=> Boolean regions

src/hamiltonian.jl, src/lattice.jl, test/test_hamiltonian.jl
Closes #130 
Introduces a new `mincoordination` kwarg in `unitcell(::Hamiltonian,...)`. This removes sites until all remaining have at least `mincoordination` neighbors. The way this works is we iterate over the mask of the supercell to eliminate any sites that have too few neighbors. This pass is repeated until no more sites are removed. As the neighbor searching reused a large part of non-trivial hamiltonian unitcell code, I had to refactor the latter so that functionality could be shared.
Example from tests:
```
h = LP.honeycomb() |> hamiltonian(hopping(1)) |> unitcell(10, region = !RP.circle(2, (0,8)))
h´ = h |> unitcell(1, mincoordination = 2)
vlplot(h, size = 300, maxdiameter = 6)
vlplot(h´, size = 300, maxdiameter = 6)
```
=> Remove dangling bonds with `mincoordination`

src/convert.jl, src/model.jl
Following the tutorial in https://www.youtube.com/watch?v=7VbXbI6OmYo by Tim Holy, I found a couple of invalidations, most notably a convert method. This PR fixes them. There are still some other invalidations but they come from dependencies, not Quantica itself.
=> Fix intrinsic invalidations

src/hamiltonian.jl, src/lattice.jl, test/test_hamiltonian.jl
PR #131 computed coordination including structural zeros, unlike the `coordination` reported by `show(::Hamiltonian)`. This PR fixes that, so that a zero hopping does not count towards `mincoordination`
=> Don't count structural zeros for mincoordination

src/Quantica.jl, src/diagonalizer.jl, src/plot_vegalite.jl
VegaLite struggles with complex plots. This is a problem when plotting eigenstates of large systems. The situation can be alleviated when the eigenstates have many values very close to zero encoded with `sitesize` in `vlplot` that in principle should not be plotted. However, to make `vlplot` faster it is necessary to explicitly exclude these table entries from the data passed to `@vlplot`.
This PR allows one to exclude these entries by passing a `mindiameter`, that is complementary to `maxdiameter`. For it to be useful for performance it probably needs to be used together with `plotlinks = false`.
Without `mindiameter` (slow)
```
vlplot(h, ψ, sitesize = abs, plotlinks = false)
```
With `mindiameter` (fast)
```
vlplot(h, ψ, sitesize = abs, plotlinks = false, mindiameter = 1)
```
This PR …
=> Add vlplot option mindiameter

src/plot_vegalite.jl
#138 introduced a bug that disabled `plotlinks` when using `mindiameter`. This fixes it.
=> Fix plotlinks with mindiameter in vlplot

src/hamiltonian.jl, src/plot_vegalite.jl, src/tools.jl
When passing a multiply degenerate subspace `s::Subspace` or a matrix `s::AbstractMatrix` to `vlplot(h, s; shaders...)`, each  basis vector or column of `s` will now be summed over after applying shaders to each. This allows to visualize observables integrated over a whole subspace (e.g. summing local density over all spin flavors).
=> Support multiple states in vlplot

src/bandstructure.jl, src/hamiltonian.jl, src/plot_vegalite.jl
This completes #140 by adding support for multiple states in current and density shaders. Thanks to @fernandopenaranda for the heads up!
This PR also tries to make CurrentShader more correct in open systems. In doing so I realized we have a serious problem here: we cannot compute currents *across* unit cell boundaries from the Bloch eigenstate alone. We also need its Bloch phases. Solving this issue requires some thought about design (e.g. what information should we store and provide about a generic eigenstate?), so I do not attempt to fix that here. For the moment, therefore, be aware that current density plots is not going to be correct in open systems.
This also introduces a stopgap fix for a problem also reported by @fernandopenaranda:
```
julia> h = LatticePresets.honeycomb() |> …
```
=> Fix in vlplot: make CurrentShader and DensityShader work with multiple states

src/lattice.jl, src/model.jl, src/presets.jl, test/test_hamiltonian.jl
The `combine` function was outdated. This updates it to properly make use of `ResolvedSelector`s when applying a `coupling` between combined Hamiltonians.
When writing tests I realized we didn't have the curried version of `transform!`, i.e. `h |> transform!(function)`, so I added that here too. Also corrected a couple of bugs in `HamiltonianPresets.twisted_graphene_bilayer` and `plusadjoint`.
=> Fix combine + curried transform!

src/hamiltonian.jl, src/tools.jl, test/test_hamiltonian.jl
This enforces that the first `dn = zero(SVector{L,Int})` harmonic exists in a Hamiltonian. We do this through an inner constructor, that also checks the dimensionality and sorting of all harmonics.
(Before this `h = LP.linear() |> hamiltonian(hopping(1)) |> unitcell((1,))` would end up without a first zero-dn harmonic)
=> Enforce harmonics invariants

docs/devdocs/singleshot.md, src/Quantica.jl, src/diagonalizer.jl, src/greens.jl, src/hamiltonian.jl, src/iterators.jl, src/plot_vegalite.jl, src/tools.jl, test/test_greens.jl
We add a new solver for the Greens function of quasi-1D Hamiltonians based on the generalized eigenvalue algorithm. 
Advantages:
- It can compute the Greens function at a fixed ω without solving all ω
- Once `g(ω, cells)` is computed for some `cells = src => dst`, any other `cells` is easy to compute.  
Disadvantages:
- It only works in 1D
- It does not exploit the sparsity of the Bloch Hamiltonian, so it scales badly with system width.
Example for the DOS of an infinite carbon nanotube
```
julia> using Plots, ProgressMeter, LinearAlgebra, Quantica
julia> h = LP.honeycomb() |> hamiltonian(hopping(1)) |> unitcell((1,-1),(30,30)) |> Quantica.wrap(2)
Hamiltonian{<:Lattice} : Hamiltonian on a 1D Lattice in 2D space
Bloch harmonics  : 3 (SparseMatrixCSC, sparse)
Harmonic size    : 120 × 120 …
```
=> Single shot Greens function in 1D

src/bandstructure.jl, src/greens.jl, test/runtests.jl, test/test_greens.jl
The convergence issue in LAPACK with direct = false will soon be fixed upstream, see https://github.com/Reference-LAPACK/lapack/issues/475 and https://github.com/Reference-LAPACK/lapack/issues/477 . Hence, there is no longer any need to make direct=true the default, as B inversion is not always possible. The updated docstring reflects this. Note that, until we get the LAPACK fix, it is safer to use this with MKL.jl instead of OpenBLAS. It does not fail and is much faster anyway.
In addition, to make direct = false a safe default we modify our filtering of invalid λ = α/β eigenvalues. It is not enough to discard λ≈0 and λ≈∞. We need to do the classification on the α, β joint eigenvalues produced by `schur(A,B)`. To do that we need to call `LAPACK.geev!` directly, bypassing Julia's …
=> Make direct = false the default for `SingleShot1D` solver

src/Quantica.jl, src/plot_makie.jl
Makie is getting deprecated in favor of backend-specific packages. 
This replaces the Makie functionality with GLMakie functionality. For the end user all should remain the same, but instead of doing
```
] add Makie
using Makie
plot(ham)
```
one should now do
```
] add GLMakie
using GLMakie
plot(ham)
```
=> Update to work with GLMakie

.github/workflows/ci.yml, src/lattice.jl, src/plot_makie.jl, test/test_greens.jl, test/test_hamiltonian.jl
Since `Lattice` was inmutable, `transform!(lat)` would transform lattice positions in place, but not bravais, returning a new lattice. Hence, `transform!(h)` also did not fully mutate in place.
Fixing this requires making `Lattice` mutable.
=> Fix transform! not mutating Bravais vectors

Project.toml, src/Quantica.jl, src/bandstructure.jl, src/diagonalizer.jl, src/greens.jl, src/hamiltonian.jl, src/lattice.jl, src/plot_vegalite.jl, src/tools.jl, test/test_bandstructure.jl, test/test_greens.jl
Closes #154 
This implements a deflating Schur algorithm that is far more precise, performant and stable than the one in master. It is developed in detail in a paper to be submitted, will post here when available. I just post a plot from the paper here
I leave some branches open for a while with alternative algorithms that were explored in developing this.
When writing tests for this I realized that the fact that `unitcell` sometimes changes the shape of the unit cell (probably because of #117) and the algorithm enlarges the unit cell using `unticell` when there are next-nearest-cell hoppings, the result can be wrong. Must fix `unitcell` in a future PR to always preserve cell shape, at least in 1D.
=> Deflating Schur algorithm for quasi1D Green functions

.github/workflows/ci.yml, src/Quantica.jl, src/effective.jl, src/greens.jl, src/hamiltonian.jl, src/tools.jl, test/test_greens.jl
This builds on top of #161
- We replace the QR deflation algorithm with a similar deflation algorithm developed by M. Wimmer, A. Akhmerov et al. that has a similar performance but is more transparent IMO. It also provides the physical retarded/advanced eigenmodes or their invariant subspaces, but does so through an LU inversion instead of a QR factorization. The numerical precision is slightly better, squeezing out one or two more significant digits of the self energy in my tests.
- We introduce a new way to build the Green's function that does not require the computation of the self-energy explicitly, which requires an inverse. This has profound consequences for the case of defective eigenmode matrices, i.e. when there is a bound state or a singularity of any other type. The idea is to …
=> Inverse-free Green's functions

.github/workflows/ci.yml, Project.toml, README.md, src/Quantica.jl, src/bandstructure.jl, test/test_bandstructure.jl
This introduces the following convenience functions for Bandstructure introspection, most defined for the moment only for 1D bandstructures for simplicity
- `minima(b::Bandstructure{1}; refinesteps = 0)`  and `maxima(b::Bandstructure; refinesteps = 0)`: finds all local minima and maxima of each band of `b`. A `refinesteps > 0` indicates the number of Newton-bisections to perform in search of the actual extremum. In this search, the Hamiltonian will be actually diagonalized in the bisection points using the same method that was used to compute `b` (through `b.diag::Diagonalizer`). Only band vertices that are local extrema without refinement will be considered as candidates for actual extrema, so that if a small gap is not resolved by the sampling of `b` it will not be found.
- `gapedge(b, …
=> Bandstructure extrema and gaps

src/bandstructure.jl, test/test_bandstructure.jl
PR #164 failed to consider the case of bands with Complex eigenvalues, even if they had negligible imaginary parts, as often happens when computing `bandstructure` using Arpack. This fixes that by always taking the real part of eigenvalues when computing extrema and gaps
=> Deal with complex spectra in band extrema

src/KPM.jl, src/ket.jl
The different behaviors of kets and ket models was not sufficiently clear in the docstrings. Hopefully this improves them a bit.
=> Improve ket, ketmodel, KPM docstrings

README.md, src/KPM.jl, src/Quantica.jl, src/hamiltonian.jl, src/ket.jl, test/test_ket.jl
The current ket model functionality `km = ketmodel(a; kw...)` builds a single or multicolumn ket model that, when applied to hamiltonian `h` with `ket(km, h)` produces a ket with amplitude `a` on *all* sites selected by `siteselector(;kw...)`. 
This is great e.g. for KPM with stochastic traces, where you want all sites in a region of interest to have independent random amplitudes. You could then just do `ketmodel(r->randn(); region = myregion)` for a single realization, or `randomkets(n, r ->randn(); region = myregion)` for `n` realizations. 
But imagine you don't want to use stochastic traces. You want the local DOS with KPM using a ket basis for all sites and orbitals in `myregion` containing `N` single-orbital sites. You want to build an N-column ket with amplitude `1` on each site, …
=> New `basiskets` ket model, and `singlesitekets` option

src/Quantica.jl, src/hamiltonian.jl, src/model.jl, src/parametric.jl, src/tools.jl, test/test_hamiltonian.jl
Our `@onsite!` and `@hopping!` create `ElementModifier <: AbstractModifier` that are great to build parametric Hamiltonians defined though modification of individual matrix elements. However they don't easily lend themselves to tasks involving the modification of whole blocks of a Hamiltonian, for example when needing to add a self-energy from a lead to a certain subset of contact sites. In that case you need a way to evaluate the self-energy block once (for a given parameter like the frequency or the contact transparency), and then apply it to a subset of sites, instead of evaluating the modification (the self energy) once per site or hopping to be modified (as `@onsite!` and `@hopping!` do).
This PR provides a new `BlockModifier <: AbstractModifier`, created with `@block!((block; …
=> New `@block!`: a block-wise `ParametricHamiltonian` modifier

.github/workflows/ci.yml, src/Quantica.jl, src/bandstructure.jl, src/tools.jl
@Max-Borovkov encountered an ambiguity issue with `qr(::SMatrix)` that arose after https://github.com/JuliaLang/julia/pull/40623. Until StaticArrays.jl catches up and/or Julialang fixes the ambiguity, this PR creates a special codepath for v1.7-beta2+ that employs the updated `qr(::SMatrix, NoPivot())` explicit syntax. Also added nightly to CI, let's see what it says.
=> Fix compatibility issues with v1.7+

src/bandstructure.jl, src/hamiltonian.jl, src/lattice.jl
Implements `spectrum(h, phi; kw...)` for unbounded Hamiltonians, where `phi` is a bloch phase
=> Implement spectrum(h, phi)

src/greenfunction.jl, test/test_greenfunction.jl
For `g::GreenFunction`, `g(0)` would fail because `eps(Int)` is not defined.
=> Fix adding eps shift to integer omega

src/hamiltonian.jl, src/types.jl, test/test_greenfunction.jl
In multiorbital systems, calling a `g(ω; params...)` of a GreenFunction of a parametric Hamiltonian performed a `call!(ph; params...)`, which updated the unflat portion of its harmonics, but not the flat portion, yielding a wrong result. This ensures that `call!(ph; params...)` does a `flat_sync!` after applying modifiers if required.
=> Fix missing flat_sync!

src/apply.jl, src/hamiltonian.jl, src/observables.jl, src/specialmatrices.jl, src/types.jl, test/test_hamiltonian.jl
We were relying on the compiler to elide the `mask_block` of Modifiers and ModelTerms when the eltype is a number, but it is not quite able to do so. Here we special case scalar eltypes so that `mask_block` is not even called. Gains of around 30% in runtime observed for ParametricHamiltonian calls of size 20000
CC: @BacAmorim
=> Optimization: don't apply mask block for scalar eltypes

docs/src/manual.md, src/docstrings.jl, src/hamiltonian.jl, test/test_hamiltonian.jl
Equivalent to `lat |> hamiltonian(model)` and `h |> hamiltonian(modifier)`, respectively. Simpler, but cannot specify `orbitals`.
=> Add `lat |> model` and `h |> modifier` syntax

.github/workflows/ci.yml, ext/QuanticaMakieExt/plotlattice.jl, ext/QuanticaMakieExt/tools.jl, src/apply.jl, src/convert.jl, src/hamiltonian.jl, src/selectors.jl, src/supercell.jl, src/tools.jl, src/types.jl, test/test_greenfunction.jl, test/test_hamiltonian.jl, test/test_plots.jl
Fixes #205 
We fix supercell by extending `applymodifier` to reapply modifiers to the supercell hamiltonian with an extra parameter that shifts (r, dr)'s to the ones of the original lattice
We fix wrap by rewriting already applied modifiers, essentially transforming the pointers of the old modifiers to new pointers to the merged (wrapped) harmonics
=> More logical behavior of wrap and supercell of ParametricHamiltonian

src/types.jl, test/test_hamiltonian.jl
As the title says. This is achieved by changing `lattice(h) = lattice(parent(h))` to `lattice(h) = lattice(hamiltonian(h))`. The previous behavior did not make sense: the reference Hamiltonian of `h` is `hamiltonian(h)`, since it is the object that is produced. `parent(h)` is only there for reference, to reset `hamiltonian(h)` when needed.
=> Make `transform(h::ParametricHamiltonian, f)` act on `hamiltonian(h)`, not `parent(h)`

docs/src/manual.md, ext/QuanticaMakieExt/plotlattice.jl, src/docstrings.jl, src/solvers/selfenergy/schur.jl, src/transform.jl, test/test_hamiltonian.jl
Add methods to `Base.reverse` and `Base.reverse!` as a fast way to switch the orientation of all Bravais vectors, which was not too straightforward with current constructors, while simplifying the code for the reverse of 1D leads
=> Reverse for `Lattice` and `AbstractHamiltonian`

docs/src/tutorial/observables.md, src/docstrings.jl, src/types.jl, test/test_greenfunction.jl, test/test_lattice.jl, test/test_plots.jl
We were not allowing empty sublattices, which led to an error if a contact was added that didn't have at least one site in each sublattice.
Since there seems to be no issue with allowing such a situation, we have relaxed the condition. Let's see if all tests pass.
=> Allow empty sublats

ext/QuanticaMakieExt/plotlattice.jl
It seems that `Makie.scatter!` is quite slow if `markersize = vector`. This is most certainly a missed optimization on their part. Until that is resolved, we add a fastpath for the common case where markersize is constant.
=> `markersize` fastpath in qplot

docs/src/tutorial/bandstructures.md, src/apply.jl, src/bands.jl, src/docstrings.jl, src/solvers/eigen.jl, test/test_bandstructure.jl
There were some thread safety bugs in multithreaded bands
- Arpack segfaults if it is used with threads because the package is currently non thread-safe (https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/86). We now use a single thread in this case (and any other solver that declares `is_thread_safe(::AbstractEigenSolver) = false`
- There was a bug in `apply(solver, h, ...)` whereby all threads would end up writing on the same Bloch matrix. Now fixed.
- We should never use multithreading with `bands(hf::Function, ...)`, because `hf` may very well not be thread-safe
=> Thread-safety fixes in `bands`

docs/src/tutorial/lattices.md, ext/QuanticaMakieExt/QuanticaMakieExt.jl, ext/QuanticaMakieExt/defaults.jl, ext/QuanticaMakieExt/docstrings.jl, ext/QuanticaMakieExt/plotbands.jl, ext/QuanticaMakieExt/plotlattice.jl, src/Quantica.jl
The new exported function `plotdefaults(; figure = (;), axis = (;))` can be used to define the default values of the `figure` and `axis` kwargs in qplot. Typical uses: fix the resolution of all subsequent plots, or the labels of their axes.
=> Configurable qplot defaults

docs/src/tutorial/observables.md, ext/QuanticaMakieExt/docstrings.jl, ext/QuanticaMakieExt/plotlattice.jl, test/test_plots.jl
There was a bug whereby a shader of type `AbstractMatrix` would be summed over rows instead of cols. 
Added missing docs also.
=> Matrix site shader should sum cols not rows

src/apply.jl, src/selectors.jl, test/test_lattice.jl
In supercell searches without a specific list of cells, we ensure BoxIterator keeps going until we find at least one site (or we exceed the maximum iterations). However `foreach_cell` did not have this check, and would stop as soon as a closed shell without hits was formed. This led to lattice slicing (using a region such as a ring around the origing) where we could fail to form a slice. Note also that `siteselector` has no `seed` option currently (unlike `supercell`), so this problem could not be worked around.
Perhaps a future refactor could employ `foreach_cell` and `foreach_site` in supercell, to be more DRY.
=> `foreach_cell` iteration should continue until at least one site is found

ext/QuanticaMakieExt/QuanticaMakieExt.jl, ext/QuanticaMakieExt/defaults.jl, ext/QuanticaMakieExt/docstrings.jl, ext/QuanticaMakieExt/plotbands.jl, ext/QuanticaMakieExt/plotlattice.jl, ext/QuanticaMakieExt/tools.jl
This build on top of #220 by splitting the defaults into four categories, for `Figure`, `Axis`, `Axis3D` and `LScene`. It also makes defaults sticky and composable: they are not overwritten by new defaults in a different category and they are merged with the explicit options passed to `qplot`.
=> Composable and sticky `qplot` defaults

src/bands.jl
The diagonalization step in `bands` is multithreaded over momenta. BLAS is also multithreaded by default. But actual diagonalization of matrices is more difficult to multithread than the loop over momenta, so it is much faster to switch to 1 single BLAS thread for the diagonalization step in `bands`, and then return to whatever it was before. The difference is specially dramatic using `EigenSolvers.LinearAlgebra`, to the point in which it is the fastest method (with multithreading) up to pretty large unit cells (like here, with 200 orbitals, 8 threads)
Master:
```julia
➜  ~ julia -t 8 -e "using Quantica, LinearAlgebra; h = HP.graphene() |> supercell(10); s=subdiv(0,2pi,50); @time bands(h, s, s);"
Step 1 - Diagonalizing: 100%|██████████████████████████████████| Time: 0:01:55
Step 2 - …
```
=> Faster `bands`: do `set_blas_threads(1)` before diagonalization, then restore

.github/workflows/ci.yml, src/bands.jl, src/convert.jl, src/greenfunction.jl, src/presets/hamiltonians.jl, src/sanitizers.jl, src/slices.jl, src/solvers/green/bands.jl, src/solvers/green/kpm.jl, src/solvers/green/schur.jl, src/solvers/green/sparselu.jl, src/tools.jl, src/types.jl, test/test_greenfunction.jl
Closes #236 
Although Quantica is coded for a generic `T<:AbstractFloat`, the GreenFunction part was not tested for `T == Float32`, only for `T == Float64`. Doing so revealed a number of issues, which are fixed in this PR
- In general, the ω argument of calls to GreenFunctions needed to be cast to the appropriate T or Complex{T} type at the beginning of the call chain.
- `GreenSolvers.SparseLU`, which relies on UMFPACK, does not support `ComplexF32` eltypes yet, so we must internally work with `ComplexF64`, taking care to return `ComplexF32` if needed without making extra copies. Tim Davis mentioned on slack that `ComplexF32` support is in the short-term to-do list for UMFPACK. At that point, the corresponding part of this PR could be simplified and generalized.
- `GreenSolvers.Schur` …
=> Add 32bit support for GreenFunctions

docs/src/tutorial/greenfunctions.md, docs/src/tutorial/observables.md, src/Quantica.jl, src/docstrings.jl, src/greenfunction.jl, src/observables.jl, src/show.jl, src/slices.jl, src/solvers/green/bands.jl, src/solvers/green/kpm.jl, src/solvers/green/spectrum.jl, src/solvers/selfenergy/generic.jl, src/solvers/selfenergy/nothing.jl, src/types.jl, test/test_greenfunction.jl, test/test_show.jl
This PR introduces `densitymatrix(::GreenSlice,...)`, which produces a `ρ::DensityMatrix` over a set of sites. To evaluate the matrix itself at a given temperature and chemical potential, and for a set of system parameters, we do `ρ(mu, kBT; params...)`
We implement three algorithms in this PR: a generic one that relies on numerical integration on the complex plane of `G(ω)*f(ω)`, another for `GreenSolver.Spectrum` and another for `GreenSolver.KPM` at zero temperature. More can be added at a later time.
=> Add `densitymatrix` observable at thermal equilibrium

docs/src/tutorial/greenfunctions.md, docs/src/tutorial/observables.md, ext/QuanticaMakieExt/plotlattice.jl, src/Quantica.jl, src/apply.jl, src/convert.jl, src/docstrings.jl, src/greenfunction.jl, src/observables.jl, src/sanitizers.jl, src/selectors.jl, src/show.jl, src/slices.jl, src/solvers/green/bands.jl, src/solvers/green/kpm.jl, src/solvers/green/spectrum.jl, src/types.jl, test/test_greenfunction.jl, test/test_lattice.jl
Closes #232 
We define a new type of `OrbitalSliceArray`, following the discussion in #232, that is designed to hold (in principle dense) matrices defined over the orbitals in a given `OrbitalSlice`. This is now the default output of fully evaluating a Green function, and of observables such as `ldos` (which gives an `OrbitalSliceVector`) and `densitymatrix` (which gives an `OrbitalSliceMatrix`). The orbital axes of an `m::OrbitalSliceArray` can be obtained with `orbaxes(m)`, and are in general a tuple of `OrbitalSliceGrouped` (which represents groups of orbitals over a lattice grouped by sites). 
For non-orbital dimensions these `orbaxes` could also be `Missing`. This possibility was brought up by @BacAmorim in #232
One critical property of this PR is that `view(::OrbitalSliceMatrix, …
=> Add `OrbitalSliceArray`

docs/make.jl, docs/src/tutorial/advanced.md, docs/src/tutorial/glossary.md, docs/src/tutorial/models.md, src/Quantica.jl, src/apply.jl, src/docstrings.jl, src/hamiltonian.jl, src/models.jl, src/observables.jl, src/sanitizers.jl, src/show.jl, src/solvers/green/kpm.jl, src/solvers/green/spectrum.jl, src/specialmatrices.jl, src/types.jl, test/test_greenfunction.jl, test/test_hamiltonian.jl, test/test_show.jl
Closes #229 
This introduces the final piece required to construct mean field models. These are one example of non-spatial models, i.e. models that cannot be written as a function of site positions, but require to know site indices and cells to then index into a mean field matrix (and OrbitalSliceMatrix to be precise, see #245).
~~The syntax for a non-spatial model is `@onsite([sitei,; params...] -> field(sitei; params...); ...)`, or `@hopping([sitei, sitej; params...] -> field(sitei, sitej; params...); ...)`, etc (this works with all types of model terms and modifiers). Note the square brackets instead of parenthesis.~~
The update syntax uses `-->` instead of `->`: 
```julia
@onsite((i; params...) --> field(i; params...); ...)
@hopping((i, j; params...) --> field(i, j; params...); ...) …
```
=> Non-spatial models (e.g. mean-field models)

ext/QuanticaMakieExt/defaults.jl, ext/QuanticaMakieExt/plotlattice.jl
This makes some tweaks to link plotting, label/font sizes, maker glyphs, etc for a smoother plotting experience with the latest Makie 0.20 changes
=> Optimize plotting for Makie 0.20

src/solvers/green/bands.jl, src/types.jl, test/test_greenfunction.jl
Closes  #252
The issue was in the construction of orbsleft and orbsright `LatticeSlice`s, which wrongly assumed that the sites coupled to a cell to the left (right) of the boundary spanned a single cell. These `LatticeSlice`s are used to compute the G0 components that, combined, implement the boundary condition.
Note: the `GS.Bands` solver still allocates too much, specially with boundaries. There is probably still some low-hanging fruit here.
=> Fix boundary construction in `GS.Bands`

src/apply.jl, src/selectors.jl, src/slices.jl, src/supercell.jl, src/types.jl, test/test_hamiltonian.jl, test/test_lattice.jl
To reduce latency and type proliferation, a generic siteselector that gets applied to a lattice becomes an `AppliedSiteSelector` with minimal type parameters. That means that e.g. `cells`, which can be many things becomes a `Vector{SVector{L,Int}}`. If `cells` was not specified (it was `missing`), it becomes an empty `Vector{SVector{L,Int}}`. The codebase knows that if it encounters an empty applied `cells`, this means "unconstrained" cells. The other option was to introduce `Union{Vector{SVector{L,Int}}, Missing}`, which I don't trust to always behave under type inference, so it was discarded.
The problem comes when one passes a function to cells, `cells = n -> is_cell_in_subset(n)` for example. If that ends up empty upon application to lattice, we currently don't distinguish this from …
=> Distinguish between null and unspecified selectors

src/solvers/green/bands.jl, test/test_greenfunction.jl
Closes #257 
The Green Bands solver (integrator over simplices of bands) needs to establish dual numbers for phase ϕ = k*r on simplex vertices. If a vertex is ϕ-degenerate and `r != 0`, the integration algorithm needs to have finite duals at a number of places, e.g. at α-coefficients which involve inverses of vandermonde determinants. There are many ways to choose the value of duals. Originally we chose them randomly (equivalent to doing a Taylor expansion around infinitesimal random simplex distortions). This led to problems of nondeterministic numeric noise. In #238 we introduced a better algorithm that would choose the duals in a deterministic way, so that the vandermonde determinants are never zero. However, the algorithm was not very elegant, as it was likely to fail for simplex …
=> New algorithm for duals in `GS.Bands`

src/builders.jl, src/docstrings.jl, src/hamiltonian.jl, src/models.jl, src/show.jl, src/specialmatrices.jl, src/supercell.jl, test/test_hamiltonian.jl, test/test_show.jl
This is a first step towards addressing #4
Here we split (internally) the process of building a Hamiltonian, which was formerly a single step `hamiltonian(lattice, model; orbitals)`,  to a multistep process:  `b = builder(lattice; orbitals)` (of type `ParametricHamiltonianBuilder`), `add!(b, model)`, and finally `hamiltonian(b)`. We can also do `push!(b, modifiers...)` to inject `Modifiers` into the builder before assembly into a Hamiltonian.
These  `builder` and `add!` functions are unexported for the moment, and meant to be used internally only. `add!` also has a method `add!(b, value, ::CellSites, ::CellSites)` to add a single or a group of values to a Hamiltonian build before assembly. This is not exported for a good reason: we don't do matrix-size checks of value for performance …
=> Factor out Hamiltonian builders

src/docstrings.jl, src/solvers/selfenergy/generic.jl, src/solvers/selfenergy/model.jl, src/solvers/selfenergy/nothing.jl, src/solvers/selfenergy/schur.jl, src/types.jl, test/test_greenfunction.jl
This adds `transform` to `attach(::GreenSlice, ::AbstractModel; transform = ..., sites = ...)`
We also check against empty contact selections, which formerly threw an obscure error. Now the error is more explicit.
=> Add `transform` keyword to generic `attach` method (second try)

docs/src/tutorial/bandstructures.md, docs/src/tutorial/glossary.md, docs/src/tutorial/greenfunctions.md, src/docstrings.jl, src/greenfunction.jl, src/hamiltonian.jl, src/solvers/green.jl, src/solvers/green/bands.jl, src/solvers/green/kpm.jl, src/solvers/green/schur.jl, src/solvers/green/sparselu.jl, src/solvers/green/spectrum.jl, src/solvers/selfenergy.jl, src/solvers/selfenergy/generic.jl, src/solvers/selfenergy/schur.jl, src/types.jl, test/test_greenfunction.jl
Closes #267 
We use the approach described in that issue: redefine `minimal_callsafe_copy` methods throughout Quantica to restore aliasing relations between subparts of objects, particularly between `GreenSolvers` and any parent `ph::ParametricHamiltonian`.
We also fixed a silly bug that called `call!` on each `ph[hybrid(dn)]` indexing, so this might even improve performance a bit. I didn't profile any potential allocations regressions of the PR. The changes are subtle and hence a bit risky.
=> Correct dealiasing in `minimal_callsafe_copy`

src/docstrings.jl, src/greenfunction.jl, src/solvers/green.jl, test/test_greenfunction.jl
It's likely that when using `view` the intention is to minimize allocations and overhead. Since `OrbitalSliceArray` does have the overhead of allocating the slice axes, we should restrict that to `getindex`, and leave `view` as lightweight as possible.
=> Make `view(gω::GreenSolution, contact_inds...)` a `SubArray` instead of an `OrbitalSliceArray`

ext/QuanticaMakieExt/QuanticaMakieExt.jl, ext/QuanticaMakieExt/docstrings.jl, ext/QuanticaMakieExt/plotlattice.jl, src/greenfunction.jl, src/types.jl, test/test_greenfunction.jl, test/test_plots.jl
=> Add `qplot(::OpenHamiltonian)`

src/models.jl, test/test_hamiltonian.jl
Closes #118 
We also reduce code repetition in macros by condensing all functionality into a single `parse_term` function
(Note that `@onsite(r -> 2, sublats)` is also accepted if `sublats` has been defined in scope, as in common functions)
=> Accept keywords after comma in parametric model macros

docs/src/tutorial/hamiltonians.md, src/apply.jl, src/builders.jl, src/convert.jl, src/docstrings.jl, src/hamiltonian.jl, src/lattice.jl, src/models.jl, src/sanitizers.jl, src/specialmatrices.jl, src/tools.jl, src/types.jl, test/test_hamiltonian.jl, test/test_lattice.jl
Closes #276 
`combine` only had real support for non-parametric `Hamiltonian`s. The reason is that parameters are implemented through modifiers that act on a selection of sites. When you combine two `ParametricHamiltonian`s, their modifiers would act on the two combined pieces, not on the original piece. With non-parametric `Hamiltonian`s this is not a problem, since all matrix elements are fixed after construction.
To support combining `ParametricHamiltonian`s we therefore need to generalize `Modifier`s to act on subblocks. Here we extend the `Intrablock` and `Interblock` machinery to act on both `AbstractModel`s and `Modifier`s. We also introduce some `promote_type` machinery to enable more precise inference of the type of the combined `AbstractHamiltonian`. We finally also restrict …
=> `combine` of `ParametricHamiltonian`s

Project.toml
PRs from #226 to #282
- `current(h::AbstractHamiltonian; direction = 1)` returns the current `Operator` along a given `direction` (#227)
- `OrbitalSliceArray`s and `CellSites`: indexing has been improved (#234, #245, #271, #277, #280)
- `GreenSolvers.Spectrum` (#240)
- `densitymatrix` observable (#241)
- `omegamap` option in `josephson` observable, to allow parameters to act as frequency (#247)
- Non-spatial models. These allow, in particular, to implement self-consistent mean field Hamiltonians (#248)
- Support for Wannier90 imports (#261, #264)
- `attach` now allows a `transform` keyword in its most general method (#263)
- Partial evaluation of `g::GreenFunction`s with `g(; params)` (#270)
- `combine` now works also with `ParametricHamiltonian`s and `ParametricModel`s as couplings …
=> Release v1.1.0

src/docstrings.jl, src/solvers/selfenergy/schur.jl, src/transform.jl, src/types.jl, test/test_greenfunction.jl, test/test_hamiltonian.jl
When doing `reverse!` of an `h::AbstractHamiltonian` we just flip the lattice Bravais vectors currently. However it is also necessary to flip the `dcell` of each harmonic. This PR does just that. It also ensures that upon use of `reverse!` in Schur solvers we do the appropriate shallow copy of the Harmonics vector in `h` (shallow = does not copy harmonic matrices, only vector of them) before reversing them. This only affects visulatization, since all the solver needs are the matrices, that remain untouched.
Example
```julia
julia> glead = LP.honeycomb() |> hopping(1) |> supercell((1, -1)) |> greenfunction(GS.Schur(boundary = 0));
julia> g = LP.honeycomb() |> hopping(1) |> supercell((4, -4)) |> supercell |>
attach(glead, region = r -> r[1] < 0.1 && r[2] > 0.1, reverse = true) |> …
```
=> Ensure `reverse!` flips harmonics

src/apply.jl, src/bands.jl
Calling `spectrum(h,...)` created an unnecessary copy of `h`. Moved the copy to where it belongs (in multithreaded `bands`).
=> Avoid extra copy in `spectrum`

Project.toml, ext/QuanticaArnoldiMethodExt.jl, ext/QuanticaArpackExt.jl, ext/QuanticaKrylovKitExt.jl, ext/QuanticaLinearMapsExt.jl, src/Quantica.jl, src/apply.jl, src/docstrings.jl, src/solvers/eigen.jl, src/solvers/green.jl, src/solvers/green/kpm.jl, src/tools.jl, test/test_bandstructure.jl, test/test_greenfunction.jl
Closes #297
We introduce extensions for LinearMaps, ArnoldiMethod, KrylovKit and Arpack.
This has revealed yet another issue with FunctionWrappers.jl, similar to #235, but not quite the same. When attempting to call `spectrum(h; solver = ...)` with an unloaded extension for the solver, it would error as expected. Then, after loading the relevant package, calling `spectrum` again would yield a weird error such as
```
julia> spectrum(h, (0,), solver = ES.ShiftInvert(ES.ArnoldiMethod(nev = 4), 0))
ERROR: TypeError: in cfunction, expected Union{}, got a value of type LinearAlgebra.Eigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
Stacktrace:
[1] macro expansion
@ ~/.julia/packages/FunctionWrappers/Q5cBx/src/FunctionWrappers.jl:137 [inlined]
[2] do_ccall
@ …
```
=> EigenSolvers as extensions

src/types.jl, test/test_hamiltonian.jl
We forgot to relink AppliedSerializer modifiers when doing`minimal_callsafe_copy(h::ParametricHamiltonian)`, which would make e.g. `bands` to ignore these modifiers.
=> Relink serializers upon ParametricHamiltonian copy

src/docstrings.jl, src/observables.jl, test/test_greenfunction.jl
Provides an unexported method `j = integrand(J::Josephson, kBT = 0.0)` to obtain the function whose integral over `ω` yields the Josephson current `J(kBT)`, where `J = josephson(...)`. The integrand can be called with `Quantica.call!(j, ω; params...)` (mutating) of `j(ω; params...)` (allocating)
=> Add `Quantica.integrand` for `josephson` currents

docs/src/tutorial/observables.md, src/docstrings.jl, src/observables.jl, src/show.jl, test/test_greenfunction.jl, test/test_show.jl
With this PR we can give a collection of complex `ωpoints` to `josephson(gs, ωpoints;...)` and `densitymatrix(gs, ωpoints; ...)` and the integration will obediently be done along a polygonal path connecting them, without any sawtooth added. Only if ωpoints are all real will a sawtooth of the given `slope` be created.
We also added a `callback` kwarg that can be used to perform any operation at each integration step.
=> Add custom integration paths and callbacks to `josephson` and `densitymatrix`

src/observables.jl, test/test_greenfunction.jl
Only affects `densitymatrix` calculations with µ != 0
=> Fix bug im #309

src/sanitizers.jl, src/tools.jl
These functions are now deprecated in 1.11. We have brought them into Quantica.
=> Bring in deprecated `permute!!` and `permutecols!!`

test/test_greenfunction.jl
We should now be able to do `ρ = densitymatrix(g[diagonal(cells = 2, kernel = SA[1 0; 0 -1])], args...)`
EDIT: This involves quite a large refactor of indexing internals, that has also resolved a number of bugs and broken tests.
=> Implement diagonal indexing in available `densitymatrix` solvers

src/types.jl, test/test_greenfunction.jl, test/test_hamiltonian.jl
Reverts pablosanjose/Quantica.jl#319
The fix in #319 was wrong. It made `copy_lattice(ph::ParametricHamiltonian)` copy the lattices of the parent and the embedded `Hamiltonian`, instead of only the parent one. In fact, the right fix is to copy only the embedded Hamiltonian because `transform` and `translate` modify `lattice(ph) = lattice(hamiltonian(ph))` only, not ` lattice(parent(ph))`, which must remain untouched. As a result the two lattices need not coincide in general.
=> Bugfix: ensure correct dealiasing of lattices in attach

docs/make.jl, docs/src/advanced/meanfield.md, src/docstrings.jl, src/meanfield.jl, src/observables.jl, src/serializer.jl, src/show.jl, src/solvers/green/schur.jl, src/specialmatrices.jl, src/types.jl, test/test_greenfunction.jl
This stores the output of calling a `MeanField` object in a new subtype of `OrbitalSliceMatrix`, called `CompressedOrbitalMatrix`, that keeps only an encoding of the original matrix. This allows to enforce hermiticity, Nambu structure and other symmetries by construction.
We also include an extension of serialize/deserialize to reinterpret as a given eltype, for compatibility with more fixed-point solvers.
=> Symmetry enforcement in meanfield

docs/src/tutorial/observables.md, src/Quantica.jl, src/docstrings.jl, src/greenfunction.jl, src/integrator.jl, src/observables.jl, src/show.jl, src/slices.jl, src/solvers/green.jl, src/solvers/green/bands.jl, src/solvers/green/internal.jl, src/solvers/green/sparselu.jl, src/specialmatrices.jl, src/tools.jl, src/types.jl, test/test_greenfunction.jl, test/test_show.jl
We introduce submodule `Paths` that contain different possible integration paths for `densitymatrix` and `josephson`. The default `densitymatrix(gs, ω0; kw...)` corresponds to `densitymatrix(gs, Paths.radial(ω0, π/4); kw...)`. This no longer an integral from `-ω0` to `ω0`, but rather along a path as shown in the figure, where the angle in orange is set to `ϕ = π/4`, and the outer arcs are taken to infinity. (The angle can of course be changed by using the full `densitymatrix(gs, Paths.radial(ω0, ϕ); kw...)` syntax)
The integral over the arcs is analytic (thanks to spectral weight normalization), so only the radial parts need to be computed numerically. Along these radial parts the path is parametrized as `ω = x * ω0 * cis(sign(x)*ϕ)` with `x` from `-Inf` to `Inf`, so that `ω0` has the …
=> Taking integration paths seriously

Project.toml, docs/src/tutorial/greenfunctions.md, src/docstrings.jl, src/show.jl, test/test_greenfunction.jl
Closes #327 
The reason for #327 was an obscure problem with stdlib Serialization caused by the following methods
```
Base.nameof(::Type{<:OrbitalSliceMatrix}) = "OrbitalSliceMatrix"
Base.nameof(::Type{<:OrbitalSliceVector}) = "OrbitalSliceVector"
Base.nameof(::Type{<:CompressedOrbitalMatrix}) = "CompressedOrbitalMatrix"
```
It might not seem at first sight, but this is a rookie mistake: those are doing pretty terrible `nameof` piracy (even though `OrbitalSliceArray` etc. are all property of Quantica), and were causing all sort of havoc, particularly in Distributed calculations (which relies on Serialization, which mysteriously choked due to the above)
=> Remove unintended `nameof` type piracy

src/docstrings.jl, src/specialmatrices.jl, test/test_greenfunction.jl
While we can index an `OrbitalSliceArray` with `sites`, and iterate over block ranges with `siteindexdict`, the very common operation of converting an `om::OrbitalSliceMatrix` into a `m::Matrix` of site blocks remains too verbose. We would do
```julia
m = [view(om, is, js) for is in siteindexdict(orbaxes(om, 1)), js in siteindexdict(orbaxes(om, 2))]
```
Or if we want each block to be an `SMatrix{4,4}`, 
```julia
m = [SMatrix{4,4}(view(om, is, js)) for is in siteindexdict(orbaxes(om, 1)), js in siteindexdict(orbaxes(om, 2))]
```
With this PR we can do instead
```julia
m = unflat(om)
```
or
```julia
m = unflat(SMatrix{4,4}, om)
```
We could even do `unflat(f, om)` with any function `f` that would act on each block.
=> `unflat` of `OrbitalSliceMatrix`

src/docstrings.jl, src/hamiltonian.jl, src/integrator.jl, src/solvers/green/schur.jl, test/test_greenfunction.jl
Since `GS.Schur` is used for 1D density matrices (which integrate over k with kF points), and in 2D green and density matrices (which integrates over a 2D Brillouin zone), it needs to know the default integration options and/or callbacks. We now pass them to `GS.Schur` and subsequent applied solvers.
Example with a 2D Hamiltonian `h2D`
```julia
xs, ys, zs = [0.0], [0.0], [0.0];
g = greenfunction(h2D, GS.Schur(; atol = 1e-3, callback = (x,y,z) -> (push!(xs, x); push!(ys, y); push!(zs, real(sum(z .^ 2))))))
ρ = densitymatrix(g[])() # uses atol and callback in the 2D integrals
```
=> Integrate options incorporated into `GS.Schur`

src/greenfunction.jl, src/specialmatrices.jl, src/tools.jl
A `post` keyword, identity by default, was broadcasted after `getindex!` of various objects. When `post === identity`, this was imposing a huge runtime penalty, at least in objects for which scalar indexing is expensive, such as `EigenProduct`. This PR skips the broadcast when unnecessary.
=> Eliminate unnecessary broadcast of identity

src/hamiltonian.jl, test/test_hamiltonian.jl
Splatting modifiers in lisp-style `applymodifiers!` was a bad idea. If you have more than 15 modifiers, this produces lots of allocations (compiler internals!). We now do  much more natural `foreach` over modifiers.
=> Remove allocations in `call!` of large parametric models

ext/QuanticaMakieExt/docstrings.jl, ext/QuanticaMakieExt/plotbands.jl, ext/QuanticaMakieExt/plotlattice.jl, ext/QuanticaMakieExt/tools.jl, test/test_plots.jl
Now, `colormap`, `sitecolormap` and `hopcolormap` accept any custom ColorScheme from ColorSchemes.jl, not only a ColorScheme name.
=> Add support for custom ColorSchemes
